name: Production Build and Deploy
on:
  push:
    branches:
      - release/production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # FontAwesome Setup
      - run: echo "@fortawesome:registry=https://npm.fontawesome.com/" > ~/.npmrc
      - run: echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}" >> ~/.npmrc
      - run: cat ~/.npmrc
      - name: Inject FontAwesome Pro
        run: npx hygen preinstall fontawesome

      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
